version: "3.9"
services:
  server:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    # command: tail -F /dev/null
    tty: true
    volumes:
      - "../../:/home/node/server"
      - /home/node/server/node_modules
    ports:
      - "${NODE_PORT}:8080"
    depends_on:
      - pg
  pg:
    image: "postgres:13.3-alpine"
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DB}"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
      - "PGADMIN_LISTEN_PORT=${PGADMIN_PORT}"
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    depends_on:
      - pg
volumes:
  pgdata: null
